### ISSUE TITLE
Empty version bump

### ISSUE THREAD

**Issue by hinrik** [duncanbeevers/rails_view_annotator#2]
Hm. You seem to have bumped the version (twice) without any other changes. Did you intend to pull in my changes first? :)

**Comment by duncanbeevers** [comment]
I did intend to pull your changes. Did it not make it into 0.0.4? Jeez, gotta stop pushing gems in the middle of the night.

**Comment by duncanbeevers** [comment]
Thanks for pointing this out. Should be good now at 0.0.5.
