### ISSUE TITLE
0.0.6 has no effect.

### ISSUE THREAD

**Issue by nadeemja** [duncanbeevers/rails_view_annotator#4]
Tested on Thin and Webrick. Doesn't work.

Using rails 3.2.1 and ruby 1.9.3-p150 on Ubuntu 11.10.

**Comment by duncanbeevers** [comment]
Are you finding you're not getting any annotation at all? I'm currently using this with thin on rails 3.2.1 ruby 1.9.3-p0 on Mac OS X 10.7.3 and I'm seeing the generated markup.

**Comment by nadeemja** [comment]
Forgive me, I thought this was supposed to annotate 'all' views, but as it says, it only works for 'partials'.

Please disregard my comments :-)

**Comment by duncanbeevers** [comment]
No biggie. Do you think it would be helpful to annotate action views as well? The tool was created to help find where deeply-nested content was generated from. I haven't had a particularly hard time figuring out what top-level view was being rendered, but if this seems helpful or would simply help provide a better sense of consistency I could look into adding that functionality.

**Comment by nadeemja** [comment]
Yes, I believe it would be helpful to annotate views too, and layouts aswell. While these are not difficult to figure out, sometimes assumptions are made that prove wrong. For example when coding with other developers.

Btw, thank you for an excellent gem :-)
