### ISSUE TITLE
Invalid comments inserted into JavaScript partials

### ISSUE THREAD

**Issue by hinrik** [duncanbeevers/rails_view_annotator#7]
When JavaScript partials are rendered, this gem inserts `<!-- -->` comments, which are invalid, and cause problems in IE7 at least.

**Comment by duncanbeevers** [comment]
Urk. I haven't written inline javascript in some time so this issue hasn't come up before. It seems like it could be an issue when we're rendering anything other than html partials (builder partials, javascript partials, etc...)

Any ideas on a good work-around for this?

**Comment by hinrik** [comment]
Maybe that solution can be improved, but it works for me.

**Comment by iainbeeston** [comment]
This problem also exists for json partials, although the pull request above fixes that (by not inserting comments if the format is unrecognised)

**Comment by duncanbeevers** [comment]
Went ahead and merged #8. Thanks for the nudge. Tagged and released 0.0.8.

**Comment by iainbeeston** [comment]
Ah... I was a little hasty. It turns out that the code from that pull request outputs comments and the original partial for .js and .html partials, but for any other partial it outputs nothing at all, not even the original content of the partial!

**Comment by duncanbeevers** [comment]
Can you throw together a PR to address this? I haven't used this gem recently, but my gut feeling is that it should be a pretty simple change.
